### PR TITLE
Fix Issue #200: Found Missing CSS and img dependencies

### PR DESCRIPTION
**Pull request by cmata23x3**
Fixed the missing file issues; Changed relative paths to find jquery_ui files && changed jstree autodetect file to find stylesheet and images. This fixes issue #200.

### CODE REVIEW

**Comment by sachazyto** [comment]
cf our Skype discussion from 20150515: We could try to change those url() locations as part of the grunt css minification process. Might be worth checking if other people ran into the same problem and what solution they came up with.

**Comment by karger** [comment]
Alternative currently proposed: load jquery-ui from cdn to take 
advantage of better latencies and caching and get proper relative urls 
for free.

**Comment by cmata23x3** [comment]
Closing this PR and will make the CDN & Grunt combo.

**Comment by karger** [comment]
Out of date

**Pull request closed without merging**
