### PR TITLE
Bug fix for #323

### PR DESCRIPTION
**Pull request by dragon96**
Previously, closing a window prematurely would fail to send to the server user data such as which threads should be marked read. Bug fix uses navigator.sendBeacon API to work around this.

### CODE REVIEW

**Comment by karger** [comment]
So I've merged and am trying this fix, but it doesn't seem to be working for me---I mark a comment, then close the doc, then reopen the doc and the comment shows unread again.

what can I look at to see what is happening?

**Comment by dragon96** [comment]
The primary changes should be in ui.concierge.js in lines 149-155: the block of code inside of the unload function. I've diffed my current working files with the commits and I'm also puzzled.

 - Between lines 154 and 155 in ui.concierge.js, can you try inserting `console.log(formData)` and recompiling?
 - Which browser are you using for this?

**Comment by karger** [comment]
I'm using chrome.  won't have time to investigate today but will look at 
this monday

**Comment by karger** [comment]
did you come up with any useful tricks for testing code that is supposed 
to run when the window gets closed?  For obvious reasons it's going to 
be hard to look at that happening in the console...

**Comment by dragon96** [comment]
I debugged by:

 - checking the option to preserve a log upon leaving the page, and console logging right before unload. Refreshing gives the same effect as closing the window.
 - inside of the JSON object I included an extra parameter like `{test: aaron}` so that I can locate my packet in the network tab of console upon refresh.
 - inside of `apps/rpc/views.py`, I printed inside of the `run` function

**Comment by karger** [comment]
Aaron, I've noticed that your pull request adds a lot of migrations files to the codebase.   Right now we don't have (many) migrations committed, because we've been kind of leaving it to each dev to make their own migrations.  We should probably fix this, but your commit isn't the right place because it actually makes no changes to the database.  Can you make a new version of your PR that doesn't commit any migration files?  thanks.

**Comment by karger** [comment]
(and if you want to rebase on the current dev branch, feel free---it won't make any conflicts, and it will make the history cleaner.)

**Comment by karger** [comment]
Now the map is rendering but the timeline is failing.  http://people.csail.mit.edu/karger/ExhibitK/demos/presidents/presidents.html

**Comment by dragon96** [comment]
I'm confused by what you mean by "the map is rendering but the timeline is failing."

**Comment by karger** [comment]
sorry aaron; that should have commented a different pull request! not 
your problem.

**Pull request merged**
