### PR TITLE
Fix the analytics page and assignment due date. Also refactor the static pages:

### PR DESCRIPTION
**Pull request by kesiena115**
* Analytics page: Refactor stylesheet, change hard-coded url and add new navbar
* Add new navbar to previously-skipped pages such as the invite-confirmation, 404 and 500 pages.
* Change the rendering mechanism of static pages by using external javascript file to add the new navbar.
* Assignment due date: Ensure that the frontend and backend code take the user's timezone into consideration when saving and displaying the saved due date.

### CODE REVIEW

**Comment by karger** [comment]
I looked at the analytics page.  There's dark blue text on a dark green background; very hard to read.

**Comment by kesiena115** [comment]
Could you please send a screenshot of the dark blue text? This is what I see: https://goo.gl/photos/YfAyqGGFMhcsX49TA

**Comment by karger** [comment]
Here's an image; I've also included a bit of the css inspector to maybe help see what's going on.  Maybe a problem with some cached css? 
image

**Comment by kesiena115** [comment]
I've fixed it. I was previously not noticing it because of cached css on my end.

**Comment by kesiena115** [comment]
Note that to deploy this pull request, you'll need to run the following commands from the root folder:

    pip install -r requirements.txt   # To install python-dateutil
    grunt  # To re-compile the updated css and js files

**Comment by karger** [comment]
Still seeing the same problem on my end.  Tried force-reloading docanalytics.css but it didn't help.
pip-install requirements.txt reported all requirements already satisfied---what did you add?

**Comment by kesiena115** [comment]
In the requirements.txt file, I added `python-dateutil>=2.4.2`. This is for the timezone problem. 

For the css of the analytics page, if you test it on my instance ([kesiena-nb.csail.mit.edu](kesiena-nb.csail.mit.edu)) it should be fine. On the dev server, you'll need to re-run `grunt` to recompile the css. I made some changes to ui.docAnalyticsView.css and tested it in incognito. Here's my screenshot:
screenshot 2016-07-28 19 25 06

**Comment by karger** [comment]
I've re-run grunt in my test instance; it didn't fix the problem.  i'll 
dig deeper.

**Pull request merged**
