### PR TITLE
WYSIWYG editor, new tagging interface and CSV file for managing sections

### PR DESCRIPTION
**Pull request by kesiena115**
**Wysiwyg editor:** This replaces the text editor with a wysiwyg editor that saves the comment as html.

**Editor panel:** Now the submit and cancel button are always visible on the screen (even if you have a small window) and the panel has been tidied up a little bit so the items are well aligned and you can select the checkboxes by clicking on the label. In addition, the editor now occupies up a bigger fraction of the sidebar.

**Tagging:** Now you'll get an autocomplete dropdown when you type @ in the editor and you can also use the checkboxes (in a popup dialog) to tag people if you prefer that. Tagged people now appear in the editor. 

**Assign sections with CSV file:** Added buttons for downloading and uploading CSV files for managing the sections. When you upload a file, the process automatically tries to detect the header row and the relevant columns (section and email) in the file by searching for "mail" and "section". It processes only rows that include students in the class. Students get identified by their email. If there're new sections in the file, they will automatically get created as part of this process. After a CSV upload, if any change is going to be made, the user sees a popup with the changes and they have the option to cancel before the data gets sent to the server.

**Search/Filter records in the section page:** This new sections page has a search/filter box that allows you to search across all cells in the table.

## Screenshots
**Tagging UI and WYSIWYG editor**
tagging-ui-1

tagging-ui-2

tagging-ui-3

**Sections Page and CSV upload**
sections-1

sections-csv-upload

### CODE REVIEW

**Comment by karger** [comment]
I've tried merging your pull request and on firefox, all the emoticon icons in the note editing pane are showing up as broken links, even though the urls of the icons (as expressed in the .emoticon css) resolve.  Maybe this involves some inconsistency in the css syntax firefox understands.  

Also on inspection, I'm noticing that there are identical css rules for .emoticon[title="curious"] in both ui.editorview.css and pdfviewer.css (one is "overriding" the identical other of course)

**Comment by kesiena115** [comment]
I'm looking into the css problem. I've just made a change to ensure that the CSS file doesn't get loaded twice (it had something to do with my earlier implementation of the tinyMCE editor). However, that doesn't fix the css. The problem is that grunt seems to remove the quotes around urls in css files when it minifies the files. I'm still searching for a way to prevent this.

**Comment by kesiena115** [comment]
Actually, my previous diagnosis of that problem was wrong. Adding the quotes didn't fix it. It seems like the css styles applied to the icons (in that manner) do not work in firefox: http://stackoverflow.com/questions/17907833/content-url-does-not-display-image-on-firefox-browser

**Comment by kesiena115** [comment]
Fixed.

**Pull request merged**
