### PR TITLE
Emoticon append

### PR DESCRIPTION
**Pull request by sshader**

### CODE REVIEW

**Comment by karger** [comment]
Some issues on testing:
1) the tags filter has a broken link/missing image: /content/views/emoticons/questionMark.png
  (may have happened if you didn't test with a clean clone of your repo, and have uncommitted files)
2) there's no "X" in the close button at the top right corner of the tags filter---it's a blank square
3) idea: what if the emoticons are vertical beside the text entry box instead of horizontal below?  would this work better?
4) we've discussed this a bit, but in my (reasonably large) browser, the comment authoring window is truncated so that all the I see is the comment entry box and the emoticons---everything else is below the fold.  Users may not notice it so not realize they can control visibility/anonymity and tag other people,   how about if you're authoring a comment, you temprarily shrink the note list and the comment window to let you enlarge the comment authoring window?

**Comment by sshader** [comment]
Hi,

I fixed the issue with the tags filter. Accidentally forgot to add those
files. As for the X, it has always been an empty box I believe. Even on
nb.mit.edu it shows up as just an empty box, so maybe this was intentional?
I will play with making the emoticons vertical as opposed to horizontal.
I've also looked into automatically resizing the three different windows as
discussed.

Thanks,

Sarah

**Comment by karger** [comment]
I don't think the blank X was intentional; I suspect some CSS was left 
out or misapplied in the pull request that updated jquery UI (I can't 
say I'm a fan of the orange color scheme either). Possibly related to 
old/open pull request #332

**Comment by karger** [comment]
Also since your in that code if you feel like tackling (new) issue #331 feel free!

**Comment by karger** [comment]
Your commit says you removed unnecessary migrations files.  What did you remove, and why are they unnecessary?

**Comment by karger** [comment]
The tags filter is failing in my test branch:
ReferenceError: $emot is not defined
http://nbdev.csail.mit.edu/content/compiled/pdfviewer_NB.js
Line 12428

**Comment by sshader** [comment]
They are the files generated by the make migrations command. I accidentally added them to a commit, but they shouldn't be necessary. I will fix the issue with $emot too once I have a chance. 

Thanks,

Sarah

**Comment by karger** [comment]
On 07/28/2016 05:39 PM, Sarah Shader wrote:
> They are the files generated by the make migrations command. I 
> accidentally added them to a commit, but they shouldn't be necessary. 
> I will fix the issue with $emot too once I have a chance.
Is it a commit we already merged?  Remember, you're welcome to rewrite 
history on the "new" part of your pull request that isn't yet merged 
into the main branch.

**Comment by sshader** [comment]
The issue with the filterwizardEmoticon should now be fixed (and live on my vm). I also removed the migration files from all my commits.

**Pull request merged**
