### PR TITLE
Restore necessary files + small patch to directory structure.

### PR DESCRIPTION
**Pull request by kpeng94**
The cleanup patch does a couple of things. 
1) Two files were mistakenly deleted during the cleanup patch. They are not used in the Gruntfile, but are used directly in some templates.
2) This reorganizes the directory structure on the frontend, splitting out views/ and lib/ directories for views and libraries. This also gets rid of the dev/ directory.

### CODE REVIEW

**Comment by karger** [comment]
If these are deleted-then-restored in your pull request, please revise 
the PR to not delete them in the first place.  If they are missing in 
the current dev head, then obviously we need this commit.

**Comment by kpeng94** [comment]
I have to close this pull request and open a new one to switch the target branch to `dev` since Github apparently does not support editing the target branch.

**Comment by karger** [comment]
i'm not sure what you mean by editing the target branch; you can do 
force pushes to a pull request in order to replace them.

**Comment by kpeng94** [comment]
If you make a pull request from A to B, you can't change the destination
branch B. You can modify A but B can't be changed.

**Pull request closed without merging**
