### PR TITLE
Fix for #326 - Do not change a user's section if they're already assigned to a section when they click the invite link sent via email.

### PR DESCRIPTION
**Pull request by kesiena115**

### CODE REVIEW

**Comment by karger** [comment]
What happens if the faculty, after inviting them to a session, assigned them to the "null" session (no session)?  Will the invite link take them back to their (no longer) assigned session?

**Comment by karger** [comment]
I've looked at your code change.  It seems you are still setting the section based on the invite (ie, problem not fixed).  Instead you changed a line that prevents an admin from accidentally removing their own admin status (this was a problem historically).  Can you explain your thinking about the changes?
thanks!

**Comment by kesiena115** [comment]
Based on the new changes, we set the section (and admin status) only if the user is not already a member of the class. If they're already a member, we simply ignore the section and admin status indicated by the invite. They'll join the class with whatever previous status they had before clicking the link.

Regarding the earlier question of 'What happens if the faculty, after inviting them to a session, assigned them to the "null" session'. Well, after sending an invite, the faculty will not be able to change the student's section until the student joins the class. Students who haven't yet joined will not show up in the list of students whose sections can be edited.

**Comment by karger** [comment]
On 9/29/2016 5:59 PM, Kesiena Owho-Ovuakporie wrote:
>
> Based on the new changes, we set the section (and admin status) only 
> if the user is not already a member of the class. If they're already a 
> member, we simply ignore the section and admin status indicated by the 
> invite. They'll join the class with whatever previous status they had 
> before clicking the link.
>
Will this be a problem if an admin decides to *add* admin status for 
someone?  (This can currently be done by sending someone a new invite 
with admin status).
>
> Regarding the earlier question of 'What happens if the faculty, after 
> inviting them to a session, assigned them to the "null" session'. 
> Well, after sending an invite, the faculty will not be able to change 
> the student's section until the student joins the class. Students who 
> haven't yet joined will not show up in the list of students whose 
> sections can be edited.
>
yes, but *after* the student joins, the faculty might move them from 
their initially invited section to a null one.  if the student then 
reuses the invite do they end up back in their originally assigned section?

**Comment by kesiena115** [comment]
One thing that may not be so obvious from looking at the diff of my changes in github is that the code that sets the section and admin status is now inside the else block. It was previously outside.

**Comment by karger** [comment]
I've looked at your code and understand what you've done.  Essentially, if there's already a membership then the invite does nothing.  This seems like a good idea in general.  To my previous point, that it won't let you make some an admin by inviting, that's probably ok, because you can make them an admin on the members list page.

But I've realized a problem.  Memberships can be deleted.  If you have a delete membership, and want to rejoin the class, and someone sends an invite, then you won't be able to rejoin the class because your deleted membership will still be there.

I think this can be fixed by filtering on deleted=false while looking for pre-existing memberships.

Another option that I think would achieve the same thing would be to delete the invite from the invite table once it is used?  Of course we'd then need to add checking for "valid invite".  But we should probably do that anyway, just to prevent people from hacking in.

Thoughts?

**Comment by kesiena115** [comment]
This will still let you make someone an admin the first time you invite them. It simply won't let you change a member's admin status or section by simply sending them an updated invite if they've already joined the class. We already have the right pages for that.

With regards to the case of re-inviting a deleted member, I think simply checking that deleted=false won't work because if we do it this way, the original invite will re-add a member if they click it a second time. It seems like it's better to delete an invite once it's been used. I'm not sure what you mean by checking for valid invite.

**Comment by kesiena115** [comment]
Regarding the problem of 
>  you won't be able to rejoin the class because your deleted membership will still be there

The work around is that the instructor can currently undelete students from the users list so there's no need to send a new invite for that.

I think this pull request is fine as a temporary solution for now. Someone else can later look through this comment thread and figure out an ideal solution that handles all scenarios appropriately

**Pull request merged**
