### PR TITLE
Whitespace fixes

### PR DESCRIPTION
**Pull request by wgxue**
Fixing whitespace issues in css and js in the dev branch (which are also present in other branches). Should make the code more readable without compromising functionality.

### CODE REVIEW

**Comment by kpeng94** [comment]
For another note, you probably want to do an interactive rebase for this and squash most of these into one commit, since they're mostly whitespace fixes.

**Comment by wgxue** [comment]
Squashed all of the whitespace fixes. Any other issues?

**Comment by wgxue** [comment]
Squashed all of the whitespace issues into one commit. Any other issues?

**Comment by karger** [comment]
This pull request seems to have replaced a vast number of double quotes with single quotes.  Was there a reason for this?  Either is fine of course, but the change makes for lots of diffs---what's the benefit?

**Comment by karger** [comment]
Also it appears that you've checked in some migrations.  Right now we aren't versioning migrations in the repo.  I intend to fix that, but for now you shouldn't be committing changes to migrations.

**Comment by kpeng94** [comment]
For the second comment, one of William's commits adds a migration file, but a later commit deletes the migration file (the PR as a whole does not add the migration). I don't think it was intended this way, but I just wanted to clarify the actual state of the PR.

**Comment by karger** [comment]
I'd prefer to clean up the commit history so the migration isn't
incorporated in the first place.  this can be done by starting at dev,
pulling the commit that adds the migration, then amending it to *not*
add the migration, then pulling followon commits as necessary.

**Comment by karger** [comment]
Due to time pressure I'm going to merge this as is; we'll fix migrations later.

**Comment by karger** [comment]
I've merged this pr but noticed some strange spacing.  In particular, lots of spaces *midline* e.g.
}   <lots of space> else {
ensemble:  <many spaces> {pfieldName: 'ensembles'}
var numnew <many space> = m.get()

are these accidental/leftovers, or is it following some specific indentation rules?

**Pull request merged**
